name: Docker CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true  # Скачиваем сабмодули (gtest), если они нужны

    - name: Build Docker Image
      run: docker build -t logger ./workspace/projects/lab08

